sudo: false
cache: bundler
language: ruby
rvm:
  - "2.3"
  - "2.4"
  - "2.5"
env:
  - RAILS_VERSION=5.0
  - RAILS_VERSION=5.1
  - RAILS_VERSION=5.2
matrix:
  exclude:
    - rvm: "2.5"
      env: RAILS_VERSION=5.0
    - rvm: "2.5"
      env: RAILS_VERSION=5.1
addons:
  postgresql: "9.5"
