sudo: false
cache: bundler
language: ruby
rvm:
  - "3.1"
env:
  - RAILS_VERSION=7.0
matrix:
  include:
    - rvm: "2.4"
      env: RAILS_VERSION=5.1
    - rvm: "2.5"
      env: RAILS_VERSION=5.2
    - rvm: "2.6"
      env: RAILS_VERSION=6.0
    - rvm: "3.1"
      env: RAILS_VERSION=7.0
addons:
  postgresql: "9.5"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
